In [35]:
import numpy as np
from scipy.linalg import svd
from numpy import dot

A = np.array([[3,2,2],[2,3,-1]])

U, S, Vh = np.linalg.svd(A)

print(U)
print("\n",S)
print("\n",Vh)
S = np.diag(S)
print("\n",sig)
B=U.dot(sig.dot(Vh))

print("\n",B)

[[-0.75774021 -0.65255634]
 [-0.65255634  0.75774021]]

 [5.06081754 2.32123368]

 [[-0.70706625 -0.68628229 -0.17051081]
 [-0.19049723  0.41706613 -0.88868816]
 [-0.68100522  0.59587957  0.42562827]]

 [[5.06081754 0.         0.        ]
 [0.         2.32123368 0.        ]]

 [[ 3.  2.  2.]
 [ 2.  3. -1.]]
